### ISSUE TITLE
Switch to POST for all routes

### ISSUE THREAD

**Issue by ryanccn** [JettChenT/encryptii-server#4]
This is not just a semantic error now.

It's causing **real-life** errors.

<img width="1212" alt="Screen Shot 2020-06-13 at 09 43 04" src="https://user-images.githubusercontent.com/47623453/84557082-77fdb900-ad5a-11ea-8465-cf0fa9057c0c.png">

Closing [ryanccn/encryptii-web#5](https://github.com/ryanccn/encryptii-web/issues/5) as this is a problem with the server.

**Comment by JettChenT** [comment]
POST available now
docs [here](https://encryptii-server.herokuapp.com/docs)
and [here](https://encryptii-server.herokuapp.com/redoc)

**Comment by JettChenT** [comment]
@ryanccn Plz switch to POST in the client side.
